model:
  backbone: 'resnext50'
  name: 'cmnet_neck_botdropfeat_doubot'
  pretrained: True
  load_weights: 'log/cmnet_neck_cmnet_neck_botdropfeat_doubot_topdrop_0/model.pth.tar-130'

data:
  type: 'image'
  sources: ['market1501', 'dukemtmcreid', 'cuhk01', 'cuhk02', 'cuhk03', 'prid']
  targets: ['market1501', 'dukemtmcreid', 'cuhk03', 'prid']
  height: 256
  width: 128
  combineall: False
  transforms: ['random_flip', 'random_crop', 'random_erase']
  root: '/home/jupyter/dataset/'
  save_dir: 'log/cmnet_neck_cmnet_neck_botdropfeat_doubot_topdrop_0'

cuhk03:
  labeled_images: True

sampler:
  train_sampler: 'RandomIdentitySampler'

loss:
  name: 'arc_supcon_focal_triplet_dropbatch_dropbotfeatures'
  arc:
    s: 30.0
    m: 0.5
  focal:
    gamma: 2.0
    weight_f: 1.0
    weight_x: 1.0
  softmax:
    label_smooth: True
  triplet:
    weight_t: 1.0
    weight_x: 1.0
  dropbatch:
    weight_db_t: 1.0
    weight_db_x: 1.0
    weight_b_db_t: 1.0
    weight_b_db_x: 1.0
    top_drop_epoch: 0
  supcon:
    weight_s: 5.0
    temperature: 0.1
    base_temperature: 0.1

train:
  optim: 'adam'
  lr: 1.
  weight_decay: 1e-4
  max_epoch: 400
  batch_size: 64
  fixbase_epoch: 0
  open_layers: ['bottleneck_global', 'bottleneck_db', 'reduction_global', 'reduction_db', 'classifier_global', 'classifier_db', 'batch_drop', 'bottleneck_drop_bottleneck_features', 'classifier_drop_bottleneck']
  lr_scheduler: 'warmup_db'
  stepsize: [50, 200, 300]
  print_freq: 300

test:
  batch_size: 300
  dist_metric: 'cosine'
  normalize_feature: True
  evaluate: False
  eval_freq: 10
  rerank: True
  visactmap: False
