model:
  name: 'top_bdnet_neck_botdropfeat_doubot'
  pretrained: True
  load_weights: 'log/top_bdnet_neck_botdropfeat_doubot_market1501_triplet_dropbatch_dropbotfeatures_topdrop_0/pretrain.pth.tar-2021-01-15-10-21-07'
  # load_weights: 'log/top_bdnet_neck_botdropfeat_doubot_market1501_triplet_dropbatch_dropbotfeatures_topdrop_0/model.pth.tar-2021-01-26-09-45-16'

data:
  type: 'image'
  sources: ['deepinsight', 'dukemtmcreid']
  targets: ['deepinsight']
  height: 256
  width: 128
  combineall: False
  transforms: ['random_flip', 'random_crop', 'random_erase']
  root: '/home/jupyter/dataset/'
  save_dir: 'log/top_bdnet_neck_botdropfeat_doubot_market1501_triplet_dropbatch_dropbotfeatures_topdrop_0'

cuhk03:
  labeled_images: True

sampler:
  train_sampler: 'RandomIdentitySampler'

loss:
  name: 'arc_supcon_focal_triplet_dropbatch_dropbotfeatures'
  arc:
    s: 30.0
    m: 1.0
  focal:
    gamma: 2.0
    weight_f: 5.0
    weight_x: 1.0
  softmax:
    label_smooth: True
  triplet:
    weight_t: 10.0
    weight_x: 1.0
  dropbatch:
    weight_db_t: 10.0
    weight_db_x: 1.0
    weight_b_db_t: 10.0
    weight_b_db_x: 1.0
    top_drop_epoch: 0
  supcon:
    weight_s: 0.5
    temperature: 0.1
    base_temperature: 0.1

train:
  optim: 'rangerlars'
  lr: 1.
  weight_decay: 1e-3
  max_epoch: 600
  batch_size: 64
  fixbase_epoch: 10
  open_layers: ['bottleneck_global', 'bottleneck_db', 'reduction_global', 'reduction_db','classifier_global', 'classifier_db', 'batch_drop', 'bottleneck_drop_bottleneck_features', 'classifier_drop_bottleneck']
  lr_scheduler: 'warmup_db'
  stepsize: [50, 200, 300]
  print_freq: 100

test:
  batch_size: 300
  dist_metric: 'cosine'
  normalize_feature: True
  evaluate: False
  eval_freq: 10
  rerank: True
  visactmap: False
